name: Deploy Full-Stack to EC2 Instances

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        instance: [1] # Adjust if you have more or fewer instances

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 Instance ${{ matrix.instance }}
      env:
        HOST: ${{ secrets[format('EC2_HOST_{0}', matrix.instance)] }}
        USER: ${{ secrets[format('EC2_USER_{0}', matrix.instance)] }}
        KEY: ${{ secrets[format('EC2_SSH_KEY_{0}', matrix.instance)] }}
        ENV_BACKEND: ${{ secrets[format('ENV_FILE_BACKEND_{0}', matrix.instance)] }}
        ENV_FRONTEND: ${{ secrets[format('ENV_FILE_FRONTEND_{0}', matrix.instance)] }}
      run: |
        echo "🚀 Iniciando despliegue en la instancia ${{ matrix.instance }}..."
        
        echo "$KEY" > deploy_key
        chmod 600 deploy_key
        
        ssh -o StrictHostKeyChecking=no -i deploy_key ${USER}@${HOST} "
          cd /opt/location-tracker
          
          # 1. Configurar git para evitar errores de ownership
          git config --global --add safe.directory /opt/location-tracker
          
          # 2. Actualizar el código desde el repositorio
          echo '📦 Actualizando código desde Git...'
          git pull origin main
          
          # --- 3. Configurar y reiniciar el Backend (Python) ---
          echo '⚙️  Configurando Backend en Python...'
          cd backend
          # Crear .env (sin sudo)
          echo '$ENV_BACKEND' > .env
          # Instalar dependencias DENTRO del entorno virtual
          /opt/location-tracker/backend/venv/bin/pip install -r requirements.txt
          # Reiniciar el proceso de PM2 con sudo
          sudo pm2 restart location-backend
          
          # --- 4. Configurar y construir el Frontend ---
          echo '🖥️  Configurando Frontend...'
          cd ../frontend
          # Crear .env (sin sudo)
          echo '$ENV_FRONTEND' > .env
          # Instalar dependencias y construir (sin sudo)
          npm install
          npm run build
          
          # --- 5. Recargar Nginx ---
          echo '🌐 Recargando Nginx...'
          sudo nginx -t && sudo systemctl reload nginx
          
          echo '✅ Despliegue completado exitosamente en la instancia ${{ matrix.instance }}'
        "